services:
  traefik:
      image: traefik:v3.5
      restart: unless-stopped
      command:
        - --api.dashboard=true
        - --accesslog=true
        - --log.level=DEBUG
        - --providers.file=true
        - --providers.file.directory=/traefik/config
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false

        - --entrypoints.web.address=:80
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.websecure.address=:443
      ports:
        - "81:80"
        - "443:443"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./traefik:/traefik"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-climbing.localhost}`)"
        - "traefik.docker.network=depottracker_traefik_web"
      environment:
        DOMAIN: ${DOMAIN:-climbing.localhost}
      networks: 
        - traefik_web

  climb_api:
    labels:
      - "traefik.docker.network=depottracker_traefik_web"
    volumes:
      - "./api:/app"

  climb_web:
    # build:
    #   context: ./web
    #   target: dev
    environment:
      REACT_APP_HOST: ${DOMAIN:-climbing.localhost}
    labels:
      - "traefik.docker.network=depottracker_traefik_web"
      - "traefik.http.services.climb_web.loadbalancer.server.port=5173"
    # labels:
      # - "traefik.http.routers.web.rule=Host(`${DOMAIN:-badlyparked.localhost}`)"
    volumes:
      - "./web/src:/app/src"
      - "./web/public:/app/public"

networks:
  traefik_web:
    external:
      false
  internal_network:
    internal: true