services:
  climb_db:
    build: ./postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      API_DB: "api"
      API_DB_USER: "${API_DB_USERNAME}"
      API_DB_PASSWORD: "${API_DB_PASSWORD}"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    networks:
      - traefik_web

  climb_web:
    build:
      context: ./web
      target: prod
      args:
        REACT_APP_HOST: ${DOMAIN:-climbing.co.uk}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.climb_web.loadbalancer.server.port=80"
      - "traefik.http.routers.climb_web.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.climb_web.rule=Host(`${DOMAIN:-climbing.localhost}`)"
      - "traefik.http.routers.climb_web.tls=true"
    networks:
      - traefik_web

  climb_api:
    build:
      context: ./api
      target: prod
    restart: unless-stopped
    depends_on:
      climb_db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.climb_api.tls=true"
      - "traefik.http.routers.climb_api.tls.certresolver=letsEncrypt"
      - "traefik.http.services.climb_api.loadbalancer.server.port=80"
      - "traefik.http.routers.climb_api.rule=Host(`${DOMAIN:-climbing.localhost}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip_api.stripprefix.prefixes=/api"
      - "traefik.http.routers.climb_api.middlewares=strip_api"
    environment:
      DOMAIN: "${DOMAIN:-climbing.localhost}"
      DATABASE_URL: "postgresql+asyncpg://${API_DB_USERNAME}:${API_DB_PASSWORD}@climb_db/api"
      SESSION_SECRET: "${SESSION_SECRET}"
      SMTP_SERVER: "${SMTP_SERVER}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_LOGIN: "${SMTP_LOGIN}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_FROM_ADDRESS: "${SMTP_FROM_ADDRESS}"

    networks:
      - internal_network
      - traefik_web
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - "./data/api/imgs/:/app/imgs"
      - "./data/api/imgs/routes/full:/app/imgs/routes/full"
      - "./data/api/imgs/routes/thumb:/app/imgs/routes/thumb"
      - "./data/api/imgs/cover_photos:/app/imgs/cover_photos"
      - "./data/api/imgs/gym:/app/imgs/gym"
      - "./data/api/videos/raw:/app/videos/raw"
      - "./data/api/videos/processed:/app/videos/processed"
      - "./data/api/videos/thumb:/app/videos/thumb"

  
networks:
  traefik_web:
    external:
      true
  internal_network:
    internal: true